name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Files to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          script: |
            cd ${{ secrets.SERVER_DIRECTORY }}
            git pull origin main --ff --no-edit
            php artisan optimize
